### ISSUE TITLE
Compatibility with old streams?

### ISSUE THREAD

**Issue by stevenvachon** [joepie91/node-bhttp#17]
Perhaps [robots-txt-parse#2](https://github.com/Woorank/robots-txt-parse/issues/2) is related.

**Comment by joepie91** [comment]
This may be an issue with Node streams themselves - I've had trouble with `pause` and `resume` in certain 0.10.x versions, which led me to implementing [this patch](https://github.com/joepie91/node-bhttp/commit/965889ee3b5ad9bcb5a3badefeb23b461da87966) internally (replacing `pause` with a pipe to the `dev-null` module).

Your application is erroring out at [this line](https://github.com/joepie91/node-bhttp/blob/f6cd01499bcf8ff5c0fe2efd44cb9f29693737b1/lib/bhttp.coffee#L498), triggered by [this line](https://github.com/Woorank/robots-txt-parse/blob/master/lib/parse.js#L110) in `robots-txt-parse`, which calls the original `resume` method on the stream. I can't really see anything in bhttp that would cause that kind of behaviour.

To me, it looks like the issue is with unavailability of `resume` in (some) 0.10 versions of Node, and that's an issue that can only be worked around by the authors of `robots-txt-parse`.

**Comment by stevenvachon** [comment]
Thanks for the response!

The robots-txt-parse dev asked about [readable-stream](https://www.npmjs.com/readable-stream). It sounds interesting.

**Comment by Janpot** [comment]
But the stream originates from `bhttp` if I understand correctly?

Wouldn't it be enough to use [`readable-stream`](https://www.npmjs.com/package/readable-stream) [here](https://github.com/joepie91/node-bhttp/blob/d08ecd1596d7e3901ff9442a8a6937b18d1b9bdf/lib/bhttp.coffee#L9) in your module to make it work properly across node versions? This should be just a drop-in replacement for you.

**Comment by joepie91** [comment]
It's not that easy, unfortunately - the stream that `bhttp` provides is the original response stream from the `http` core module, with some extra properties attached. I don't have any control over what underlying stream implementation it were to use.

Fundamentally, `robots-txt-parse` can't really rely on the version of a stream that is being passed into it, whether that is a stream from `bhttp` or another module entirely. It therefore seems to me that this would have to be fixed in `robots-txt-parse`, to really accomplish predictable behaviour.

Perhaps [this](https://www.npmjs.com/package/stream-combiner2) would be of use for `robots-txt-parse`? I'm unsure whether it would solve this particular issue, but it claims to upgrade streams.

**Comment by Janpot** [comment]
> Looking at the code again, it's not entirely clear to me why resume is being called to begin with?

If I recall correctly, but it's been a while, it had to do with stream quirks in the `event-stream` package.

**Comment by stevenvachon** [comment]
Thank you both!! Issue resolved in latest `robots-txt-parse` release with `event-stream` package.

**Comment by stevenvachon** [comment]
Oops, `resume` was removed instead.
